.pragma library

// Code generated by internal/desktop/genactivity.go. DO NOT EDIT.
//
// The Jarvix activity feed's display vocabulary, compiled from the Go table
// in internal/desktop/activity.go — the source of truth, and the only place
// it is tested (ADR 0013 keeps QML display-only). Rows arrive from the
// daemon already worded; this file only knows which glyph each row kind
// draws. Regenerate with:
//
//     go generate ./internal/desktop

var glyphs = {
  "artifact": "󰈤",
  "assistant": "󰍩",
  "automation": "󰃰",
  "cancelled": "󰓛",
  "context": "󰍹",
  "desktop": "󰖲",
  "error": "󰀦",
  "gate": "󰋗",
  "intent": "󰉁",
  "memory": "󰂺",
  "model": "󰧑",
  "refusal": "󰜺",
  "routine": "󰒪",
  "script": "󰆍",
  "timings": "󰅐",
  "tool": "󰒓",
  "turn": "󰇘",
  "typing": "󰌌",
  "wake": "󰍮",
  "you": "󰍬"
}

var fallbackGlyph = "󰇘"

// glyphFor mirrors desktop.ActivityGlyph: an unknown kind — a newer daemon
// may add kinds this build has never heard of — draws the dots glyph rather
// than a hole.
function glyphFor(kind) {
  return glyphs[String(kind || "")] || fallbackGlyph
}
