.pragma library

// Code generated by internal/desktop/genbarstate.go. DO NOT EDIT.
//
// The Jarvix bar widget's state vocabulary, compiled from the Go table in
// internal/desktop/barstatus.go — the source of truth, and the only place
// these rules are tested (ADR 0013 keeps QML display-only). Regenerate with:
//
//     go generate ./internal/desktop
//
// Glyphs are Nerd Font (Material Design) characters; each state has its own
// shape so the widget never depends on colour alone.

// One record per state. Keys match the `state` field of a state.changed
// event (docs/ipc.md), plus the three the widget synthesises — not-running,
// error, and working — and the two background-listening rows the wake state
// selects.
var states = {
  "acting": { key: "acting", glyph: "󰉁", label: "Running a command", detail: "A matched intent is executing", urgent: false, pulse: false, dim: false },
  "awaiting_confirmation": { key: "awaiting_confirmation", glyph: "󰋗", label: "Waiting for your answer", detail: "A tool call needs confirming", urgent: true, pulse: true, dim: false },
  "cancelling": { key: "cancelling", glyph: "󰜺", label: "Cancelling", detail: "Stopping the current turn", urgent: false, pulse: false, dim: false },
  "error": { key: "error", glyph: "󰀦", label: "Jarvix hit a problem", detail: "The last turn failed", urgent: true, pulse: false, dim: false },
  "idle": { key: "idle", glyph: "󰀘", label: "Jarvix is ready", detail: "Click to open the conversation", urgent: false, pulse: false, dim: false },
  "listening": { key: "listening", glyph: "󰍬", label: "Listening", detail: "The microphone is open", urgent: false, pulse: true, dim: false },
  "not-running": { key: "not-running", glyph: "󰒲", label: "Jarvix is not running", detail: "Start it: systemctl --user start jarvixd", urgent: false, pulse: false, dim: true },
  "responding": { key: "responding", glyph: "󰍩", label: "Responding", detail: "Writing the answer", urgent: false, pulse: false, dim: false },
  "speaking": { key: "speaking", glyph: "󰕾", label: "Speaking", detail: "Reading the answer aloud", urgent: false, pulse: false, dim: false },
  "thinking": { key: "thinking", glyph: "󰧑", label: "Thinking", detail: "Working out an answer", urgent: false, pulse: true, dim: false },
  "transcribing": { key: "transcribing", glyph: "󱑽", label: "Transcribing", detail: "Turning what you said into text", urgent: false, pulse: false, dim: false },
  "wake-armed": { key: "wake-armed", glyph: "󰍮", label: "Listening for the wake word", detail: "The microphone is open; audio stays on this machine until you say the wake word", urgent: false, pulse: false, dim: false },
  "wake-muted": { key: "wake-muted", glyph: "󰍭", label: "Microphone muted", detail: "Background listening is off; run jarvix unmute to resume", urgent: false, pulse: false, dim: false },
  "working": { key: "working", glyph: "󰇘", label: "Working", detail: "Jarvix is busy", urgent: false, pulse: false, dim: false }
}

// statusFor mirrors desktop.BarStatusFor. Precedence: a dead socket beats any
// state (a state read from a dead connection is stale); a held error beats the
// state (the daemon returns to idle after a failed turn, so the state alone
// would erase the failure); an active session beats the wake state (the
// session states already say the microphone is open); between sessions the
// wake state decides, so "idle with a capture process running" never draws as
// plain "ready"; an unrecognised state reads as "Working" rather than "ready".
function statusFor(connected, state, errorMessage, wake) {
  if (!connected) return states["not-running"]
  var message = String(errorMessage || "").trim()
  if (message !== "") {
    var failed = states["error"]
    return {
      key: failed.key, glyph: failed.glyph, label: failed.label,
      detail: message, urgent: failed.urgent, pulse: failed.pulse, dim: failed.dim
    }
  }
  var name = String(state || "")
  if (name === "" || name === "idle") {
    var listening = String(wake || "")
    if (listening === "armed") return states["wake-armed"]
    if (listening === "muted") return states["wake-muted"]
    return states["idle"]
  }
  return states[name] || states["working"]
}

// tooltip is the hover and accessible text: label, plus detail when there is
// one. Mirrors BarState.Tooltip().
function tooltip(status) {
  if (!status) return ""
  if (!status.detail) return status.label
  return status.label + " — " + status.detail
}

// The states that are phases of a session — the ones whose tooltip earns an
// elapsed counter and live tool detail. Mirrors desktop.busyBarStateKeys.
var busyStates = {
  "acting": true,
  "awaiting_confirmation": true,
  "cancelling": true,
  "listening": true,
  "responding": true,
  "speaking": true,
  "thinking": true,
  "transcribing": true,
  "working": true
}

// formatElapsed mirrors desktop.formatActivityElapsed: "12s", then "1m05s"
// past a minute.
function formatElapsed(sec) {
  sec = Math.max(0, Math.floor(sec || 0))
  if (sec < 60) return sec + "s"
  var s = sec % 60
  return Math.floor(sec / 60) + "m" + (s < 10 ? "0" : "") + s + "s"
}

// liveTooltip mirrors desktop.LiveTooltip: the state's label plus the most
// informative detail of the moment — the confirmation question while one is
// pending, the running tool's own label or name while one is in flight, the
// static detail otherwise — prefixed with how long this phase has run.
// Non-session states keep their plain tooltip.
function liveTooltip(status, elapsedSec, tool, toolDetail, question) {
  if (!status) return ""
  if (!busyStates[status.key]) return tooltip(status)
  var detail = status.detail
  var q = String(question || "")
  var td = String(toolDetail || "")
  var tn = String(tool || "")
  if (status.key === "awaiting_confirmation" && q !== "") detail = q
  else if (td !== "") detail = td.replace(/…$/, "")
  else if (tn !== "") detail = "running " + tn
  if (Math.floor(elapsedSec || 0) > 0) detail = formatElapsed(elapsedSec) + " · " + detail
  if (detail === "") return status.label
  return status.label + " — " + detail
}

// The panel's menu, in draw order. Every command already exists: the plugin's
// own IPC surface — the same handler "jarvix window" and a clicked
// notification go through — or the CLI. Mirrors desktop.BarActionsFor.
var allActions = [
  { key: "start", glyph: "󰐥", label: "Start Jarvix", detail: "systemctl --user start jarvixd", command: "systemctl --user start jarvixd", onlyWhenDown: true, onlyWhenWake: "" },
  { key: "mute", glyph: "󰍭", label: "Mute the microphone", detail: "Stop listening for the wake word", command: "jarvix mute", onlyWhenDown: false, onlyWhenWake: "armed" },
  { key: "unmute", glyph: "󰍮", label: "Resume background listening", detail: "Listen for the wake word again", command: "jarvix unmute", onlyWhenDown: false, onlyWhenWake: "muted" },
  { key: "window", glyph: "󰖲", label: "Conversation window", detail: "Show or hide the full conversation", command: "omarchy-shell jarvix toggleWindow", onlyWhenDown: false, onlyWhenWake: "" },
  { key: "new", glyph: "󰐙", label: "New conversation", detail: "Forget the current thread and start fresh", command: "jarvix new", onlyWhenDown: false, onlyWhenWake: "" },
  { key: "settings", glyph: "󰒓", label: "Settings", detail: "Voice, activation, AI, and advisors", command: "omarchy-shell jarvix openSettings", onlyWhenDown: false, onlyWhenWake: "" }
]

function actions(connected, wake) {
  var listening = String(wake || "")
  return allActions.filter(function (a) {
    if (a.onlyWhenDown && connected) return false
    if (a.onlyWhenWake !== "" && (!connected || a.onlyWhenWake !== listening)) return false
    return true
  })
}

// Icons for the kinds `jarvix artifacts --json` reports. Anything else —
// the CLI falls back to the bare extension — gets the generic file glyph, so
// a row never draws with a hole where its icon should be.
var artifactGlyphs = {
  "diagram": "󰒪",
  "document": "󰧮",
  "sketch": "󰽉",
  "source": "󰅩",
  "spreadsheet": "󰱿"
}

var fileGlyph = "󰈤"
var folderGlyph = "󰝰"

function artifactGlyph(kind) {
  return artifactGlyphs[String(kind || "")] || fileGlyph
}
