.pragma library

// Code generated by internal/desktop/genbarstate.go. DO NOT EDIT.
//
// The Jarvix bar widget's state vocabulary, compiled from the Go table in
// internal/desktop/barstatus.go — the source of truth, and the only place
// these rules are tested (ADR 0013 keeps QML display-only). Regenerate with:
//
//     go generate ./internal/desktop
//
// Glyphs are Nerd Font (Material Design) characters; each state has its own
// shape so the widget never depends on colour alone.

// One record per state. Keys match the `state` field of a state.changed
// event (docs/ipc.md), plus the three the widget synthesises — not-running,
// error, and working — and the two background-listening rows the wake state
// selects. `short` is the bar chip's word, empty where a state carries no
// chip at all.
var states = {
  "acting": { key: "acting", glyph: "󰉁", label: "Running a command", short: "Running", detail: "A matched intent is executing", urgent: false, pulse: false, dim: false },
  "awaiting_confirmation": { key: "awaiting_confirmation", glyph: "󰋗", label: "Waiting for your answer", short: "Confirm?", detail: "A tool call needs confirming", urgent: true, pulse: true, dim: false },
  "cancelling": { key: "cancelling", glyph: "󰜺", label: "Cancelling", short: "Cancelling", detail: "Stopping the current turn", urgent: false, pulse: false, dim: false },
  "error": { key: "error", glyph: "󰀦", label: "Jarvix hit a problem", short: "Problem", detail: "The last turn failed", urgent: true, pulse: false, dim: false },
  "idle": { key: "idle", glyph: "󰀘", label: "Jarvix is ready", short: "", detail: "Click to open the conversation", urgent: false, pulse: false, dim: false },
  "listening": { key: "listening", glyph: "󰍬", label: "Listening", short: "Listening", detail: "The microphone is open", urgent: false, pulse: true, dim: false },
  "not-running": { key: "not-running", glyph: "󰒲", label: "Jarvix is not running", short: "", detail: "Start it: systemctl --user start jarvixd", urgent: false, pulse: false, dim: true },
  "responding": { key: "responding", glyph: "󰍩", label: "Responding", short: "Responding", detail: "Writing the answer", urgent: false, pulse: false, dim: false },
  "speaking": { key: "speaking", glyph: "󰕾", label: "Speaking", short: "Speaking", detail: "Reading the answer aloud", urgent: false, pulse: false, dim: false },
  "thinking": { key: "thinking", glyph: "󰧑", label: "Thinking", short: "Thinking", detail: "Working out an answer", urgent: false, pulse: true, dim: false },
  "transcribing": { key: "transcribing", glyph: "󱑽", label: "Transcribing", short: "Transcribing", detail: "Turning what you said into text", urgent: false, pulse: false, dim: false },
  "wake-armed": { key: "wake-armed", glyph: "󰍮", label: "Listening for the wake word", short: "", detail: "The microphone is open; audio stays on this machine until you say the wake word", urgent: false, pulse: false, dim: false },
  "wake-muted": { key: "wake-muted", glyph: "󰍭", label: "Microphone muted", short: "", detail: "Background listening is off; run jarvix unmute to resume", urgent: false, pulse: false, dim: false },
  "working": { key: "working", glyph: "󰇘", label: "Working", short: "Working", detail: "Jarvix is busy", urgent: false, pulse: false, dim: false }
}

// statusFor mirrors desktop.BarStatusFor. Precedence: a dead socket beats any
// state (a state read from a dead connection is stale); a held error beats the
// state (the daemon returns to idle after a failed turn, so the state alone
// would erase the failure); an active session beats the wake state (the
// session states already say the microphone is open); between sessions the
// wake state decides, so "idle with a capture process running" never draws as
// plain "ready"; an unrecognised state reads as "Working" rather than "ready".
function statusFor(connected, state, errorMessage, wake) {
  if (!connected) return states["not-running"]
  var message = String(errorMessage || "").trim()
  if (message !== "") {
    var failed = states["error"]
    return {
      key: failed.key, glyph: failed.glyph, label: failed.label,
      short: failed.short, detail: message, urgent: failed.urgent,
      pulse: failed.pulse, dim: failed.dim
    }
  }
  var name = String(state || "")
  if (name === "" || name === "idle") {
    var listening = String(wake || "")
    if (listening === "armed") return states["wake-armed"]
    if (listening === "muted") return states["wake-muted"]
    return states["idle"]
  }
  return states[name] || states["working"]
}

// tooltip is the hover and accessible text: label, plus detail when there is
// one. Mirrors BarState.Tooltip().
function tooltip(status) {
  if (!status) return ""
  if (!status.detail) return status.label
  return status.label + " — " + status.detail
}

// The states that are phases of a session — the ones whose tooltip earns an
// elapsed counter and live tool detail. Mirrors desktop.busyBarStateKeys.
var busyStates = {
  "acting": true,
  "awaiting_confirmation": true,
  "cancelling": true,
  "listening": true,
  "responding": true,
  "speaking": true,
  "thinking": true,
  "transcribing": true,
  "working": true
}

// formatElapsed mirrors desktop.formatActivityElapsed: "12s", then "1m05s"
// past a minute.
function formatElapsed(sec) {
  sec = Math.max(0, Math.floor(sec || 0))
  if (sec < 60) return sec + "s"
  var s = sec % 60
  return Math.floor(sec / 60) + "m" + (s < 10 ? "0" : "") + s + "s"
}

// liveTooltip mirrors desktop.LiveTooltip: the state's label plus the most
// informative detail of the moment — the confirmation question while one is
// pending, the running tool's own label or name while one is in flight, the
// static detail otherwise — prefixed with how long this phase has run.
// Non-session states keep their plain tooltip.
function liveTooltip(status, elapsedSec, tool, toolDetail, question) {
  if (!status) return ""
  if (!busyStates[status.key]) return tooltip(status)
  var detail = status.detail
  var q = String(question || "")
  var td = String(toolDetail || "")
  var tn = String(tool || "")
  if (status.key === "awaiting_confirmation" && q !== "") detail = q
  else if (td !== "") detail = td.replace(/…$/, "")
  else if (tn !== "") detail = "running " + tn
  if (Math.floor(elapsedSec || 0) > 0) detail = formatElapsed(elapsedSec) + " · " + detail
  if (detail === "") return status.label
  return status.label + " — " + detail
}

// chipLabel mirrors desktop.BarChipLabel: the short words the bar draws beside
// its glyph, with the elapsed count on the states that earn one, and "" where
// the widget should draw the bare icon alone (issue #158).
function chipLabel(status, elapsedSec) {
  if (!status || !status.short) return ""
  if (busyStates[status.key] && Math.floor(elapsedSec || 0) > 0) {
    return status.short + " " + formatElapsed(elapsedSec)
  }
  return status.short
}

// The conversation window's pending assistant turn (issue #158). Everything
// below mirrors internal/desktop/pending.go, which is where it is tested; the
// window renders the string and decides nothing (ADR 0013).

// The present-tense action class per tool, mirroring desktop.toolPhrases —
// the same table the permission gate asks its short question from, so the two
// surfaces cannot name one capability two ways.
var toolDoing = {
  "advisor.ask": "Consulting another assistant",
  "config.delete_entry": "Deleting a configuration entry",
  "config.write_entry": "Saving a configuration entry",
  "config.write_setting": "Changing one of your settings",
  "intent.run": "Running your custom command",
  "knowledge.refresh": "Refreshing one of your feeds",
  "memory.forget": "Forgetting one of your saved facts",
  "routine.run": "Running one of your routines",
  "script.run": "Running one of your scripts",
  "shell.run": "Running a shell command",
  "typing.press_key": "Typing on your keyboard",
  "typing.type_text": "Typing on your keyboard"
}

// toolActionDoing mirrors desktop.ToolActionDoing. An unlisted tool names
// itself rather than borrowing a friendlier word.
function toolActionDoing(tool) {
  var name = String(tool || "")
  if (name === "") return ""
  return toolDoing[name] || ("Running " + name)
}

// pendingTurnLabel mirrors desktop.PendingTurnLabel: what Jarvix is doing, from
// the session state and the tool in flight. "" means there is no pending turn —
// which is how the window knows to stop showing one rather than leave it
// counting up after the turn ended.
function pendingTurnLabel(state, tool, toolDetail) {
  var s = states[String(state || "")]
  if (!s || !busyStates[s.key]) return ""
  if (s.key === "awaiting_confirmation") return s.label
  var name = String(tool || "").trim()
  var td = String(toolDetail || "").trim()
  if (s.key === "speaking" && name === "" && td === "") return ""
  var detail = td.replace(/…$/, "").trim()
  if (detail !== "") return detail
  var phrase = toolActionDoing(name)
  if (phrase !== "") return phrase
  return s.label
}

// How long a wait must run before it starts saying how long. Mirrors
// desktop.PendingElapsedThresholdSec.
var pendingElapsedThresholdSec = 2

// pendingTurnLine mirrors desktop.PendingTurnLine. elapsedSec is measured from
// the daemon's own phase start (state.changed's since_ms, conversation.get's
// state_since_ms), never from when this window happened to start watching.
function pendingTurnLine(state, tool, toolDetail, elapsedSec) {
  var label = pendingTurnLabel(state, tool, toolDetail)
  if (label === "") return ""
  var sec = Math.floor(elapsedSec || 0)
  if (sec >= pendingElapsedThresholdSec) return label + " · " + formatElapsed(sec)
  return label
}

// How a pending turn resolves when the user cancelled. Mirrors
// desktop.PendingTurnCancelled.
var pendingTurnCancelled = "Cancelled"

// pendingTurnFailed mirrors desktop.PendingTurnFailed: the activity feed's own
// sentence for the same failure, so one error is never worded twice.
function pendingTurnFailed(stage, message) {
  var text = String(message || "").trim()
  if (text === "") text = "The last turn failed"
  var at = String(stage || "").trim()
  if (at === "") return text
  return "Failed at " + at + " — " + text
}

// The panel's menu, in draw order. Every command already exists: the plugin's
// own IPC surface — the same handler "jarvix window" and a clicked
// notification go through — or the CLI. Mirrors desktop.BarActionsFor.
var allActions = [
  { key: "start", glyph: "󰐥", label: "Start Jarvix", detail: "systemctl --user start jarvixd", command: "systemctl --user start jarvixd", onlyWhenDown: true, onlyWhenWake: "" },
  { key: "mute", glyph: "󰍭", label: "Mute the microphone", detail: "Stop listening for the wake word", command: "jarvix mute", onlyWhenDown: false, onlyWhenWake: "armed" },
  { key: "unmute", glyph: "󰍮", label: "Resume background listening", detail: "Listen for the wake word again", command: "jarvix unmute", onlyWhenDown: false, onlyWhenWake: "muted" },
  { key: "window", glyph: "󰖲", label: "Conversation window", detail: "Show or hide the full conversation", command: "omarchy-shell jarvix toggleWindow", onlyWhenDown: false, onlyWhenWake: "" },
  { key: "new", glyph: "󰐙", label: "New conversation", detail: "Forget the current thread and start fresh", command: "jarvix new", onlyWhenDown: false, onlyWhenWake: "" },
  { key: "settings", glyph: "󰒓", label: "Settings", detail: "Voice, activation, AI, and advisors", command: "omarchy-shell jarvix openSettings", onlyWhenDown: false, onlyWhenWake: "" }
]

function actions(connected, wake) {
  var listening = String(wake || "")
  return allActions.filter(function (a) {
    if (a.onlyWhenDown && connected) return false
    if (a.onlyWhenWake !== "" && (!connected || a.onlyWhenWake !== listening)) return false
    return true
  })
}

// Icons for the kinds `jarvix artifacts --json` reports. Anything else —
// the CLI falls back to the bare extension — gets the generic file glyph, so
// a row never draws with a hole where its icon should be.
var artifactGlyphs = {
  "diagram": "󰒪",
  "document": "󰧮",
  "sketch": "󰽉",
  "source": "󰅩",
  "spreadsheet": "󰱿"
}

var fileGlyph = "󰈤"
var folderGlyph = "󰝰"

function artifactGlyph(kind) {
  return artifactGlyphs[String(kind || "")] || fileGlyph
}
