.pragma library

// Code generated by internal/desktop/genbarstate.go. DO NOT EDIT.
//
// The Jarvix bar widget's state vocabulary, compiled from the Go table in
// internal/desktop/barstatus.go — the source of truth, and the only place
// these rules are tested (ADR 0013 keeps QML display-only). Regenerate with:
//
//     go generate ./internal/desktop
//
// Glyphs are Nerd Font (Material Design) characters; each state has its own
// shape so the widget never depends on colour alone.

// One record per state. Keys match the `state` field of a state.changed
// event (docs/ipc.md), plus the three the widget synthesises: not-running,
// error, and working.
var states = {
  "acting": { key: "acting", glyph: "󰉁", label: "Running a command", detail: "A matched intent is executing", urgent: false, pulse: false, dim: false },
  "awaiting_confirmation": { key: "awaiting_confirmation", glyph: "󰋗", label: "Waiting for your answer", detail: "A tool call needs confirming", urgent: true, pulse: true, dim: false },
  "cancelling": { key: "cancelling", glyph: "󰜺", label: "Cancelling", detail: "Stopping the current turn", urgent: false, pulse: false, dim: false },
  "error": { key: "error", glyph: "󰀦", label: "Jarvix hit a problem", detail: "The last turn failed", urgent: true, pulse: false, dim: false },
  "idle": { key: "idle", glyph: "󰀘", label: "Jarvix is ready", detail: "Click to open the conversation", urgent: false, pulse: false, dim: false },
  "listening": { key: "listening", glyph: "󰍬", label: "Listening", detail: "The microphone is open", urgent: false, pulse: true, dim: false },
  "not-running": { key: "not-running", glyph: "󰒲", label: "Jarvix is not running", detail: "Start it: systemctl --user start jarvixd", urgent: false, pulse: false, dim: true },
  "responding": { key: "responding", glyph: "󰍩", label: "Responding", detail: "Writing the answer", urgent: false, pulse: false, dim: false },
  "speaking": { key: "speaking", glyph: "󰕾", label: "Speaking", detail: "Reading the answer aloud", urgent: false, pulse: false, dim: false },
  "thinking": { key: "thinking", glyph: "󰧑", label: "Thinking", detail: "Working out an answer", urgent: false, pulse: true, dim: false },
  "transcribing": { key: "transcribing", glyph: "󱑽", label: "Transcribing", detail: "Turning what you said into text", urgent: false, pulse: false, dim: false },
  "working": { key: "working", glyph: "󰇘", label: "Working", detail: "Jarvix is busy", urgent: false, pulse: false, dim: false }
}

// statusFor mirrors desktop.BarStatusFor. Precedence: a dead socket beats any
// state (a state read from a dead connection is stale); a held error beats the
// state (the daemon returns to idle after a failed turn, so the state alone
// would erase the failure); an unrecognised state reads as "Working" rather
// than "ready".
function statusFor(connected, state, errorMessage) {
  if (!connected) return states["not-running"]
  var message = String(errorMessage || "").trim()
  if (message !== "") {
    var failed = states["error"]
    return {
      key: failed.key, glyph: failed.glyph, label: failed.label,
      detail: message, urgent: failed.urgent, pulse: failed.pulse, dim: failed.dim
    }
  }
  var name = String(state || "")
  if (name === "") return states["idle"]
  return states[name] || states["working"]
}

// tooltip is the hover and accessible text: label, plus detail when there is
// one. Mirrors BarState.Tooltip().
function tooltip(status) {
  if (!status) return ""
  if (!status.detail) return status.label
  return status.label + " — " + status.detail
}

// The panel's menu, in draw order. Every command already exists: the plugin's
// own IPC surface — the same handler "jarvix window" and a clicked
// notification go through — or the CLI. Mirrors desktop.BarActionsFor.
var allActions = [
  { key: "start", glyph: "󰐥", label: "Start Jarvix", detail: "systemctl --user start jarvixd", command: "systemctl --user start jarvixd", onlyWhenDown: true },
  { key: "window", glyph: "󰖲", label: "Conversation window", detail: "Show or hide the full conversation", command: "omarchy-shell jarvix toggleWindow", onlyWhenDown: false },
  { key: "new", glyph: "󰐙", label: "New conversation", detail: "Forget the current thread and start fresh", command: "jarvix new", onlyWhenDown: false },
  { key: "settings", glyph: "󰒓", label: "Settings", detail: "Voice, activation, AI, and advisors", command: "omarchy-shell jarvix openSettings", onlyWhenDown: false }
]

function actions(connected) {
  return allActions.filter(function (a) { return !(a.onlyWhenDown && connected) })
}

// Icons for the kinds `jarvix artifacts --json` reports. Anything else —
// the CLI falls back to the bare extension — gets the generic file glyph, so
// a row never draws with a hole where its icon should be.
var artifactGlyphs = {
  "diagram": "󰒪",
  "document": "󰧮",
  "sketch": "󰽉",
  "source": "󰅩",
  "spreadsheet": "󰱿"
}

var fileGlyph = "󰈤"
var folderGlyph = "󰝰"

function artifactGlyph(kind) {
  return artifactGlyphs[String(kind || "")] || fileGlyph
}
