#!/bin/bash
# Install a local wake-word detector for Jarvix: a Python venv with
# openWakeWord, its pretrained ONNX models, and the streaming helper script.
#
# Background listening is opt-in and this is why: it needs a model, and a
# model is a download and a runtime. Nothing here talks to the network after
# the install, and nothing here writes audio anywhere — the helper scores
# frames on stdin and answers on stdout (see wake/wake_detect.py).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/jarvix"
BIN_DIR="${HOME}/.local/bin"
VENV="$DATA_DIR/wake-venv"

echo "Installing the Jarvix wake-word detector into $DATA_DIR"
mkdir -p "$DATA_DIR" "$BIN_DIR"

if [[ ! -x "$VENV/bin/python" ]]; then
  echo "Creating Python venv..."
  python3 -m venv "$VENV"
fi

echo "Installing openwakeword (ONNX runtime, no GPU needed)..."
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet openwakeword onnxruntime numpy

echo "Downloading the pretrained models..."
"$VENV/bin/python" -c 'import openwakeword.utils as u; u.download_models()'

install -m755 "$REPO_DIR/wake/wake_detect.py" "$DATA_DIR/wake_detect.py"

# A tiny launcher so activation.wake_command stays the single word
# "jarvix-wake" rather than a venv path nobody would type.
cat > "$BIN_DIR/jarvix-wake" <<LAUNCHER
#!/bin/sh
# Generated by scripts/setup-wake.sh — the Jarvix wake-word detector.
exec "$VENV/bin/python" "$DATA_DIR/wake_detect.py" "\$@"
LAUNCHER
chmod +x "$BIN_DIR/jarvix-wake"

cat <<'DONE'

Installed. Turn background listening on:

  jarvix config set activation.mode=wake_word
  systemctl --user restart jarvixd
  jarvix doctor            # confirms the detector and reports the capture pid
  jarvix status            # shows whether the microphone is open, and which pid

Then just say it: "Jarvix, what's my disk usage?"

Two things worth knowing before you leave it on:

  * openWakeWord ships no model for "Jarvix". The closest pretrained model is
    "hey jarvis", which is what this installs and what `jarvix status` will
    report. It responds to "hey Jarvis" far more reliably than to "Jarvix" —
    train your own model if you want the real word (see the openWakeWord
    docs; point activation.wake_word at the .onnx file).
  * `jarvix mute` kills the capture process outright, and the bar widget
    shows a struck-through microphone while it is muted. Check it whenever
    you want: `jarvix status` prints the pid, and `ps -p <pid>` either finds
    it or does not.
DONE
